### ISSUE TITLE
Comfy Updated with a Deprecation Change Causing Error

### ISSUE THREAD

**Issue by camoody1** [Acly/comfyui-inpaint-nodes#47]
```
Traceback (most recent call last):
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-inpaint-nodes\__init__.py", line 21, in <module>
    from . import nodes
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-inpaint-nodes\nodes.py", line 14, in <module>
    from comfy_extras.chainner_models.types import PyTorchModel
ModuleNotFoundError: No module named 'comfy_extras.chainner_models.types'
```
Hoping you can make changes to your nodes to work with this change.

Thank you

**Comment by laitianwen** [comment]
I also appear after the update of this problem, please ask you to solve it?

**Comment by lyx0206331** [comment]
The same as you, how to resolve it?

**Comment by sevenlucas7** [comment]
I also appear after the update of this problem

**Comment by toyxyz** [comment]
Same here!

**Comment by Acly** [comment]
Done

**Comment by freshlesh3** [comment]
> Done

Sorry, I'm still getting this error when loading Krita AI. I used a fresh install of Comfy, updated Krita and installed your custom nodes and still getting the missing node error.

**Comment by Jayho2008** [comment]
I have the same problem, I have installed, but it was showing missing the inpaint nodes, Please help

**Comment by Jayho2008** [comment]
> Done

how I can you fix it ? please help
