### ISSUE TITLE
inpaint_v25.fooocus.patch and inpaint_v26.fooocus.patch models cannot be loaded

### ISSUE THREAD

**Issue by lunatico67** [Acly/comfyui-inpaint-nodes#93]
![Error--FooocusX](https://github.com/user-attachments/assets/ae54eee9-9fb5-411b-8c4c-d99de70b1ee2)

I just updated Comfyui-inpaint-nodes and the inpaint_v25.fooocus.patch and inpaint_v26.fooocus.patch models cannot be loaded in Load Fooocus Inpaint node, does not recognize them. What happened with this latest update, how can I fix it?   Is it possible to go back to the previous version?

**Comment by dmac-afk** [comment]
Also having this issue. Tried on a fresh comfy install with no other custom nodes enabled

**Comment by lunatico67** [comment]
> Also having this issue. Tried on a fresh comfy install with no other custom nodes enabled

The problem has arisen with the latest update of comfyui-inpaint-nodes. Until today it was working perfectly.

**Comment by freecoderwaifu** [comment]
Same issue, using a custom ComfyUI install without any other nodes except the ones needed by Krita AI Diffusion. 

Thought it could be due to custom A1111/Forge paths with `extra_model_paths.yaml` because to the console log message, but deleting that .yaml didn't fix it.

Console log:
```

FETCH DATA from: E:\variousAI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[ERROR] An error occurred while retrieving information for the 'INPAINT_LoadFooocusInpaint' node.
Traceback (most recent call last):
  File "E:\variousAI\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "E:\variousAI\ComfyUI_windows_portable\ComfyUI\server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\variousAI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-inpaint-nodes\nodes.py", line 115, in INPUT_TYPES
    "head": (folder_paths.get_filename_list("inpaint"),),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\variousAI\ComfyUI_windows_portable\ComfyUI\folder_paths.py", line 326, in get_filename_list
    out = get_filename_list_(folder_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\variousAI\ComfyUI_windows_portable\ComfyUI\folder_paths.py", line 287, in get_filename_list_
    folders = folder_names_and_paths[folder_name]
              ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'inpaint'

[ERROR] An error occurred while retrieving information for the 'INPAINT_LoadInpaintModel' node.
Traceback (most recent call last):
  File "E:\variousAI\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "E:\variousAI\ComfyUI_windows_portable\ComfyUI\server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\variousAI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-inpaint-nodes\nodes.py", line 317, in INPUT_TYPES
    "model_name": (folder_paths.get_filename_list("inpaint"),),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\variousAI\ComfyUI_windows_portable\ComfyUI\folder_paths.py", line 326, in get_filename_list
    out = get_filename_list_(folder_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\variousAI\ComfyUI_windows_portable\ComfyUI\folder_paths.py", line 287, in get_filename_list_
    folders = folder_names_and_paths[folder_name]
              ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'inpaint'
```

**Comment by dmac-afk** [comment]
> > Also having this issue. Tried on a fresh comfy install with no other custom nodes enabled
> 
> The problem has arisen with the latest update of comfyui-inpaint-nodes. Until today it was working perfectly.

Confirming this. Reverting to the last commit fixed the issue for me.

**Comment by lunatico67** [comment]
Confirming this. Reverting to the last commit fixed the issue for me.

Please dmac-afk  How did you get back to the last commit?

**Comment by dmac-afk** [comment]
In your terminal go to the inpaint-nodes directory

/Your_Comfy_Install_Path/custom_nodes/comfyui-inpaint-nodes

git checkout 6fcdf55

**Comment by Acly** [comment]
Should work now with latest version

**Comment by lunatico67** [comment]
Thanks to all for the help.
I have updated it again and it still does not work. It does not detect files with .patch extension:
1- inpaint.fooocus.patch
2- inpaint_v25.fooocus.patch
3- inpaint_v26.fooocus.patch
I have never studied computer science but it is clear that this is a problem that has arisen from these last two updates. Until today it worked perfectly.

**Comment by lunatico67** [comment]
dmac-afk thanks for the help.
C:\Users\Luna\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-inpaint-nodes>git clone
and what should I type after git clone?

**Comment by lunatico67** [comment]
> In your terminal go to the inpaint-nodes directory
> 
> /Your_Comfy_Install_Path/custom_nodes/comfyui-inpaint-nodes
> 
> git checkout [6fcdf55](https://github.com/Acly/comfyui-inpaint-nodes/commit/6fcdf5523d53e82029e0af6cf4887e17d182b7ec)

dmac-afk thanks for the help.
C:\Users\Luna\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-inpaint-nodes>git clone
and what should I type after git clone?

**Comment by Acly** [comment]
Please try to update again if you're still having issues.

**Comment by lunatico67** [comment]
> Please try to update again if you're still having issues.

Acly a lot of thanks, now works perfect!
